"""empty message

Revision ID: 082dbdb1f3d3
Revises: 9b43211fdb9c
Create Date: 2025-09-15 23:17:28.494733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082dbdb1f3d3'
down_revision = '9b43211fdb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_agent_conversation_id', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('assistant_agent_conversation_id')

    # ### end Alembic commands ###
